#!/bin/bash
# Backend environment variables setup helper

echo "=== Burstlet Backend Environment Variables ==="
echo ""
echo "Copy these values to DigitalOcean App Platform settings:"
echo "https://cloud.digitalocean.com/apps/86641fa9-3771-4cd8-98eb-3a63e89be2b5/settings"
echo ""
echo "=== Database ==="
echo "DATABASE_URL: postgresql://postgres:[YOUR-SUPABASE-PASSWORD]@db.cmfdlebyqgjifwmfvquu.supabase.co:5432/postgres"
echo ""
echo "=== Supabase ==="
echo "SUPABASE_URL: https://cmfdlebyqgjifwmfvquu.supabase.co"
echo "SUPABASE_SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtZmRsZWJ5cWdqaWZ3bWZ2cXV1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNjUzODY5OSwiZXhwIjoyMDUyMTE0Njk5fQ.LJuJ0r9S3-lI0rnBHhLwBqx0B6t9JZUrtGjO3g2Msfo"
echo ""
echo "=== JWT ==="
echo "JWT_SECRET: $(openssl rand -base64 32)"
echo ""
echo "=== Email (Resend) ==="
echo "RESEND_API_KEY: [Get from https://resend.com/api-keys]"
echo ""
echo "=== AI Services ==="
echo "OPENAI_API_KEY: [Get from https://platform.openai.com/api-keys]"
echo "HAILUOAI_API_KEY: [Get from HailuoAI dashboard]"
echo "MINIMAX_API_KEY: [Get from MiniMax dashboard]"
echo ""
echo "=== Stripe ==="
echo "STRIPE_SECRET_KEY: [Get from https://dashboard.stripe.com/apikeys]"
echo "STRIPE_WEBHOOK_SECRET: [Will be generated when creating webhook endpoint]"
echo ""
echo "=== Redis ==="
echo "REDIS_URL: redis://default:[password]@[host]:[port]"
echo "(You can use Upstash Redis: https://upstash.com)"
echo ""
echo "=== Social Media APIs ==="
echo "YOUTUBE_CLIENT_ID: [Get from Google Cloud Console]"
echo "YOUTUBE_CLIENT_SECRET: [Get from Google Cloud Console]"
echo "TIKTOK_CLIENT_ID: [Get from TikTok Developer Portal]"
echo "TIKTOK_CLIENT_SECRET: [Get from TikTok Developer Portal]"
echo "INSTAGRAM_CLIENT_ID: [Get from Meta Developer Portal]"
echo "INSTAGRAM_CLIENT_SECRET: [Get from Meta Developer Portal]"
echo "TWITTER_CLIENT_ID: [Get from Twitter Developer Portal]"
echo "TWITTER_CLIENT_SECRET: [Get from Twitter Developer Portal]"
echo ""
echo "=== After configuring all variables ==="
echo "1. The app will automatically deploy"
echo "2. Get the app URL from DigitalOcean dashboard"
echo "3. Update NEXT_PUBLIC_API_URL in Vercel to the app URL"
echo "4. Configure Stripe webhook endpoint with the app URL"