#!/bin/bash

echo "🔍 Checking for missing environment variables"
echo "==========================================="
echo ""

# Variables you have
echo "✅ Variables you already have:"
echo "- CSRF_SECRET ✓"
echo "- ADMIN_OVERRIDE_TOKEN ✓"
echo "- SESSION_SECRET ✓"
echo "- ENCRYPTION_KEY ✓"
echo "- FRONTEND_URL ✓"
echo "- STORAGE_BUCKET ✓"
echo "- SUPABASE_ANON_KEY ✓"
echo "- DATABASE_URL ✓"
echo "- SUPABASE_URL ✓"
echo "- SUPABASE_SERVICE_KEY ✓"
echo "- JWT_SECRET ✓"
echo "- NODE_ENV ✓"
echo "- PORT ✓"
echo "- REDIS_URL ✓"
echo ""

echo "❌ Missing variables (add these now):"
echo ""
echo "# AI Service Keys (use these exact placeholders for now)"
echo "OPENAI_API_KEY=sk-placeholder"
echo "HAILUOAI_API_KEY=hailuoai-placeholder"
echo "MINIMAX_API_KEY=minimax-placeholder"
echo ""
echo "# Email Service"
echo "RESEND_API_KEY=re_placeholder"
echo ""
echo "# Payment Processing"
echo "STRIPE_SECRET_KEY=sk_test_placeholder"
echo "STRIPE_WEBHOOK_SECRET=whsec_placeholder"
echo ""
echo "# OAuth (use these exact placeholders for now)"
echo "YOUTUBE_CLIENT_ID=placeholder"
echo "YOUTUBE_CLIENT_SECRET=placeholder"
echo "TIKTOK_CLIENT_ID=placeholder"
echo "TIKTOK_CLIENT_SECRET=placeholder"
echo "INSTAGRAM_CLIENT_ID=placeholder"
echo "INSTAGRAM_CLIENT_SECRET=placeholder"
echo "TWITTER_CLIENT_ID=placeholder"
echo "TWITTER_CLIENT_SECRET=placeholder"
echo ""
echo "📝 Add these to DigitalOcean and click Save"
echo "   This will trigger a redeployment"