#!/bin/bash
# Deploy backend to Railway

echo "=== Deploying to Railway ==="
echo ""
echo "Railway is a modern platform that makes deployment simple."
echo ""

# Check if railway CLI is installed
if ! command -v railway &> /dev/null; then
    echo "Railway CLI not installed. Installing..."
    echo ""
    echo "Option 1: Using npm (recommended)"
    echo "  npm install -g @railway/cli"
    echo ""
    echo "Option 2: Using Homebrew"
    echo "  brew install railway"
    echo ""
    echo "After installation, run this script again."
    exit 1
fi

echo "Steps to deploy:"
echo ""
echo "1. Login to Railway:"
echo "   railway login"
echo ""
echo "2. Initialize project (run from backend directory):"
echo "   cd backend"
echo "   railway init"
echo ""
echo "3. Set environment variables:"
echo "   railway variables set DATABASE_URL=your-supabase-url"
echo "   railway variables set SUPABASE_URL=https://cmfdlebyqgjifwmfvquu.supabase.co"
echo "   railway variables set SUPABASE_SERVICE_KEY=your-service-key"
echo "   railway variables set JWT_SECRET=$(openssl rand -base64 32)"
echo "   railway variables set NODE_ENV=production"
echo "   railway variables set PORT=3001"
echo ""
echo "4. Deploy:"
echo "   railway up"
echo ""
echo "5. Get your app URL:"
echo "   railway open"
echo ""
echo "Railway provides:"
echo "- Automatic HTTPS"
echo "- GitHub integration"
echo "- Easy environment variables"
echo "- Logs and monitoring"
echo "- $5 free credit monthly"
echo ""
echo "Alternative: Deploy via GitHub"
echo "1. Go to https://railway.app"
echo "2. Click 'Start a New Project'"
echo "3. Select 'Deploy from GitHub repo'"
echo "4. Choose codevanmoose/burstlet"
echo "5. Set root directory to 'backend'"
echo "6. Add environment variables"
echo ""