#!/bin/bash
# OAuth setup guide for all platforms

echo "=== OAuth Setup Guide ==="
echo ""
echo "This guide helps you set up OAuth for Google and social media platforms."
echo ""
echo "=== 1. Google OAuth (Required for Login) ==="
echo "1. Go to: https://console.cloud.google.com"
echo "2. Create new project or select existing"
echo "3. Enable APIs:"
echo "   - Google+ API"
echo "   - YouTube Data API v3"
echo "4. Create credentials:"
echo "   - Go to Credentials > Create Credentials > OAuth 2.0 Client ID"
echo "   - Application type: Web application"
echo "   - Name: Burstlet"
echo "   - Authorized redirect URIs:"
echo "     - https://burstlet-gilt.vercel.app/api/auth/callback/google"
echo "     - http://localhost:3000/api/auth/callback/google (for dev)"
echo "5. Copy Client ID and Client Secret"
echo ""
echo "=== 2. YouTube (Uses Google OAuth) ==="
echo "Already configured with Google OAuth above!"
echo "Scopes needed: youtube.upload, youtube.readonly"
echo ""
echo "=== 3. TikTok Developer ==="
echo "1. Go to: https://developers.tiktok.com"
echo "2. Create app in 'Manage apps'"
echo "3. Add products: 'Login Kit' and 'Content Posting API'"
echo "4. Configure:"
echo "   - Redirect URIs: https://[your-backend-url]/api/platforms/tiktok/callback"
echo "   - Scopes: user.info.basic, video.upload"
echo "5. Submit for review (required for production)"
echo ""
echo "=== 4. Instagram Basic Display ==="
echo "1. Go to: https://developers.facebook.com"
echo "2. Create app > Consumer"
echo "3. Add 'Instagram Basic Display' product"
echo "4. Configure:"
echo "   - Valid OAuth Redirect URIs: https://[your-backend-url]/api/platforms/instagram/callback"
echo "   - Deauthorize Callback URL: https://[your-backend-url]/api/platforms/instagram/deauth"
echo "5. Add Instagram Test User for development"
echo ""
echo "=== 5. Twitter API v2 ==="
echo "1. Go to: https://developer.twitter.com"
echo "2. Create project and app"
echo "3. Set up OAuth 2.0:"
echo "   - Type: Web App"
echo "   - Callback URL: https://[your-backend-url]/api/platforms/twitter/callback"
echo "   - Website URL: https://burstlet-gilt.vercel.app"
echo "4. Request elevated access for media upload"
echo ""
echo "=== Environment Variables Needed ==="
echo "Frontend (Vercel):"
echo "- GOOGLE_CLIENT_ID"
echo "- GOOGLE_CLIENT_SECRET"
echo ""
echo "Backend (DigitalOcean):"
echo "- YOUTUBE_CLIENT_ID (same as Google)"
echo "- YOUTUBE_CLIENT_SECRET (same as Google)"
echo "- TIKTOK_CLIENT_ID"
echo "- TIKTOK_CLIENT_SECRET"
echo "- INSTAGRAM_CLIENT_ID"
echo "- INSTAGRAM_CLIENT_SECRET"
echo "- TWITTER_CLIENT_ID"
echo "- TWITTER_CLIENT_SECRET"
echo ""
echo "Note: Most platforms require app review for production use."
echo "Start with Google OAuth for basic functionality."
echo ""