#!/bin/bash
# Redis setup guide using Upstash

echo "=== Redis Setup with Upstash ==="
echo ""
echo "Upstash provides a serverless Redis database perfect for Burstlet's queue system."
echo ""
echo "1. Create Upstash Account:"
echo "   Go to: https://console.upstash.com/register"
echo ""
echo "2. Create Redis Database:"
echo "   - Click 'Create Database'"
echo "   - Name: burstlet-redis"
echo "   - Type: Regional"
echo "   - Region: US-East-1 (or closest to your backend)"
echo "   - Enable: Eviction"
echo "   - Click 'Create'"
echo ""
echo "3. Get Connection Details:"
echo "   From the database dashboard, copy:"
echo "   - Endpoint: xxxxxx.upstash.io:xxxxx"
echo "   - Password: xxxxxxxxxx"
echo ""
echo "4. Format Redis URL:"
echo "   redis://default:[password]@[endpoint]"
echo "   Example: redis://default:abc123@us1-example.upstash.io:12345"
echo ""
echo "5. Add to DigitalOcean:"
echo "   Add REDIS_URL environment variable with the formatted URL"
echo ""
echo "Alternative: Local Redis with Docker"
echo "   docker run -d -p 6379:6379 redis:alpine"
echo "   REDIS_URL=redis://localhost:6379"
echo ""
echo "Free Tier Limits:"
echo "   - 10,000 commands per day"
echo "   - 256MB storage"
echo "   - Perfect for development and small production apps"
echo ""