#!/bin/bash
# Stripe configuration guide

echo "=== Stripe Setup Guide for Burstlet ==="
echo ""
echo "1. Go to Stripe Dashboard: https://dashboard.stripe.com"
echo ""
echo "2. Create Products (Products > Add product):"
echo "   a) Starter Plan"
echo "      - Name: Starter"
echo "      - Description: Perfect for individuals getting started"
echo "      - Price: \$29/month (recurring)"
echo "      - Features: 100 video generations, 500 blog posts"
echo ""
echo "   b) Professional Plan"
echo "      - Name: Professional"
echo "      - Description: For growing content creators"
echo "      - Price: \$99/month (recurring)"
echo "      - Features: 500 videos, unlimited blogs, priority support"
echo ""
echo "   c) Enterprise Plan"
echo "      - Name: Enterprise"
echo "      - Description: For teams and agencies"
echo "      - Price: \$299/month (recurring)"
echo "      - Features: Unlimited everything, dedicated support"
echo ""
echo "3. Get API Keys (Developers > API keys):"
echo "   - Publishable key: pk_live_..."
echo "   - Secret key: sk_live_..."
echo ""
echo "4. Create Webhook Endpoint (Developers > Webhooks > Add endpoint):"
echo "   - Endpoint URL: https://[your-backend-url]/api/billing/webhook"
echo "   - Events to listen for:"
echo "     ✓ customer.subscription.created"
echo "     ✓ customer.subscription.updated"
echo "     ✓ customer.subscription.deleted"
echo "     ✓ invoice.payment_succeeded"
echo "     ✓ invoice.payment_failed"
echo "   - Get the Signing secret: whsec_..."
echo ""
echo "5. Update Environment Variables:"
echo "   Frontend (Vercel):"
echo "   - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
echo ""
echo "   Backend (DigitalOcean):"
echo "   - STRIPE_SECRET_KEY"
echo "   - STRIPE_WEBHOOK_SECRET"
echo ""
echo "6. Test with Stripe CLI (optional):"
echo "   stripe login"
echo "   stripe listen --forward-to localhost:3001/api/billing/webhook"
echo ""